### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by standardpointer** [kevinaangstadt/CS340-Summer21-Notes#2]
What should the consensus be for the file format? When I first pulled the repo, there was an untitled Jupyter file for lecture nine. I'm not sure if we want to stick with that?

**Comment by DigitalSRC** [comment]
I am not sure about the Jupyter file for lecture 9, I didn't have that when I cloned the repo. Other than that, I personally would suggest to simply provide a format and be like "this is what I think it should be" and then we can comment on concerns, additions, or removals/replacements as needed till we have something comfortable. Ill let you take a crack at it first sense you suggested it (evil laugh).

**Comment by DigitalSRC** [comment]
I think we should use a text file for the files. I don't want to use an external program like jupyter. I also think markdown files might be the way to go cause you can make headers and bullet points etc.

**Comment by kevinaangstadt** [comment]
It looks like we have settled on plain markdown files for the formatting.
