### ISSUE TITLE
Review Claiming

### ISSUE THREAD

**Issue by cailemieuxmack** [kevinaangstadt/CS340-Summer21-Notes#28]
Hey Guys. Lets use this as a place to claim which notes we are reviewing

**Comment by musicalkeyboard1234** [comment]
I thought these were going to be assigned? I guess I'll choose to review one of Kevin's notes then.

**Comment by cailemieuxmack** [comment]
It appears that the reviews are being assigned by Kevin, so disregard this.

**Comment by kevinaangstadt** [comment]
Correct.  I will tag you in a comment on the PR to assign a review.
