### ISSUE TITLE
Template for formatting

### ISSUE THREAD

**Issue by superslalomracer** [kevinaangstadt/CS340-Summer21-Notes#33]
I have just drafted a Lecture_template.md file that I will make a pull request for. I was thinking we could all agree, once pending PRs are approved, that we each had until a certain day to edit the template, then we should conform to the one format, more or less. 

I propose, once PRs are approved, we give it two days to edit the template as we see fit, then anything in main can be pulled by anyone for formatting.

**Comment by standardpointer** [comment]
Regarding the formatting, I personally don't think that an overview is that necessary. I think it's safe to assume that the readers are either us or Kevin in this context. Moreover, when I'm writing notes for class, I find it more cumbersome to write an overview when I'm already including headers and whatnot for each topic.

**Comment by epuer18** [comment]
I agree with musicalkeyboard1234, I think since lectures are often pretty concise and have 1 or 2 topics an overview is not as necessary. We can edit the template accordingly but do think that while things get approved or not I would personally prefer to skip that section. Otherwise thanks for putting this up!

**Comment by kevinaangstadt** [comment]
How does this relate back to #17?  Just want to make sure that the style guide is consistent.

**Comment by epuer18** [comment]
I think the spacing from the template is consistent with the one in #17. I do think the titles themselves are different, however. From looking at other notes, I think that maybe title heads in the template can be ## (double hashes) as opposed to (####). I do not know if I should submit @superslalomracer 's template with the corrections I am proposing, or if we should wait for the template to be added to the repo first. Then,  I can make a commit with the modifications.

**Comment by superslalomracer** [comment]
It's probably best to let the template file be accepted, then edit it yourself so you can get a pull request on another person's file. If the template is not approved, however, I'll have to change it beforehand.
