### ISSUE TITLE
File Naming Convention

### ISSUE THREAD

**Issue by epuer18** [kevinaangstadt/CS340-Summer21-Notes#9]
I think it is important to have some sort of naming convention for our note files. I feel like not only does this make the repo seem more organized at a glance but also allows for easy searching of files and sorting if ever needed. I personally propose a Lecture_{Number}.md system but if other people have suggestions or already named files we can further decide. Also, I am a fan of leading zeros for single-digit numbers, e.g. Lecture_05.md, so that these are sorted before say Lecture_10.md.

**Comment by kevinaangstadt** [comment]
It looks like we have consensus for a naming convention.  @epuer18 would you like to add this convention to some sort of overarching README or style guide via a PR?

**Comment by epuer18** [comment]
Yes, I can add this to the README.
